version: '3'

vars:
  # If you run bare environment or activated venv, set '' (blank string)
  RUN_PYTHON: 'uv run'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen'

includes:
  docs: './docs'
