name: 'Deploy doc'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - name: Run document
        run: |
          uv sync --frozen
          uv run make -C docs mini18n-dirhtml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/mini18n-dirhtml
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
